export const skillItemEn = [
  { img: "github.svg", skill: "Github" },
  { img: "css.svg", skill: "CSS" },
  { img: "html.svg", skill: "HTML" },
  { img: "js.svg", skill: "Javascript" },
  { img: "nextjs.svg", skill: "Next JS" },
  { img: "node-js.svg", skill: "Node JS" },
  { img: "react.svg", skill: "React Native" },
  { img: "redux.svg", skill: "Redux" },
  { img: "supabase.svg", skill: "Supabase" },
  { img: "tailwind.svg", skill: "Tailwind" },
  { img: "ts.svg", skill: "Typescript" },
  { img: "vite.svg", skill: "Vite" },
  { img: "prisma.svg", skill: "Prisma" },
];

export const slugs = [
    "supabase",
    "typescript",
    "javascript",
    "react",
    "html5",
    "css3",
    "express",
    "nextdotjs",
    "prisma",
    "amazonaws",
    "postgresql",
    "vercel",
    "testinglibrary",
    "cypress",
    "docker",
    "git",
    "jira",
    "github",
    "visualstudiocode",
    "sonarqube",
    "figma",
    "tailwind",
    "vite",
    "redux",
    "prisma"
  ];
