export const dataProjectEn = [
  {
    id: "eventmanagement",
    thumbnail: "eventmanagement.png",
    judul: "Event Management",
    desc: "A website designed to make it easier for users to organize and manage events, from ordering tickets, registering participants, to real-time data reporting.",
    demo: false,
    includeBE: true,
    githubLink: "https://github.com/RadidDesfandri/Event-management.git",
    demoLink: "",
    framework: [
      { img: "nextjs.svg" },
      { img: "ts.svg" },
      { img: "tailwind.svg" },
      { img: "prisma.svg" },
      { img: "node-js.svg" },
    ],
  },
  {
    id: "propertyrentapp",
    thumbnail: "rentapp.png",
    judul: "Property Rent Apps",
    desc: "This website is a property rental platform designed to provide convenience for property owners and seekers. Through this application, users can find properties such as villas or hotels quickly and easily. The advanced features available allow users to search for properties based on location, price, capacity and category, so that each search becomes more specific and tailored to their needs.",
    demo: true,
    includeBE: true,
    githubLink: "https://github.com/purwadhikafullstack/JCWD0408-02.git",
    demoLink: "https://property-rent-app-iota.vercel.app",
    framework: [
      { img: "nextjs.svg" },
      { img: "ts.svg" },
      { img: "tailwind.svg" },
      { img: "prisma.svg" },
      { img: "node-js.svg" },
    ],
  },
  {
    id: "realtimechat",
    thumbnail: "realtimechat.png",
    judul: "Realtime Chat",
    desc: "This application is a communication platform that allows users to send messages to each other in real time, enabling users to see incoming messages instantly as they are sent by the other party. Its main features include the ability to send text, images, and videos, as well as create group chats.",
    demo: true,
    includeBE: true,
    githubLink: "https://github.com/RadidDesfandri/Realtime-Chat",
    demoLink: "https://realtime-chat-nine-chi.vercel.app",
    framework: [
      { img: "nextjs.svg" },
      { img: "ts.svg" },
      { img: "tailwind.svg" },
      { img: "prisma.svg" },
      { img: "mongodb.svg" },
      { img: "pusher.svg" },
    ],
  },
  {
    id: "companyprofile",
    thumbnail: "robotcompany.png",
    judul: "Company Profile",
    desc: "A Website to showcase innovations, products and services from robotics companies, with the aim of helping them reach more potential clients and partners.",
    demo: true,
    includeBE: false,
    githubLink: "https://github.com/RadidDesfandri/Company-profile.git",
    demoLink: "https://company-profile-mu-lake.vercel.app",
    framework: [
      { img: "nextjs.svg" },
      { img: "ts.svg" },
      { img: "tailwind.svg" },
    ],
  },
];
